input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://db:5432/veteransdb"
    jdbc_user => "dima"
    jdbc_password => "root"
    
    # Исправленный запрос с использованием :sql_last_value
    statement => "SELECT * FROM news WHERE updated_at > :sql_last_value"
    
    schedule => "*/5 * * * *"
    
    # Настройки для инкрементальной загрузки
    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"
    last_run_metadata_path => "/usr/share/logstash/data/.logstash_jdbc_last_run_news"
    
    # Опционально: начальное значение (не sql_last_value!)
    # record_last_run => true
    # clean_run => false
  }
}

filter {
  mutate {
    add_field => {
      "indexed_at" => "%{[@timestamp]}"
      "database" => "postgresql"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "postgres-data-%{+YYYY.MM.dd}"
    document_id => "%{id}"
  }
  stdout { codec => rubydebug }
}